/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.ListasCirculares;
import Modelo.ListasSimples;
import controlador.Dibujo;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Usuario
 */
public class DibujoNodoCircular extends javax.swing.JPanel {

    Dibujo db=new Dibujo();
    String nombre;
    int cont=0;
    ListasCirculares lc=new ListasCirculares();
    public DibujoNodoCircular(int cont,String nombre,ListasCirculares lc) {
        initComponents();
        this.setOpaque(true);
        this.setSize(new Dimension(3000,20));
        this.setBackground(Color.black);
        this.cont=cont;
        this.nombre=nombre;
        this.lc=lc;
    }
     public void paint(Graphics g){
    Icon imagen=new ImageIcon(getClass().getResource("/imagenes/nododob3.png"));
    Icon imagen2 = new ImageIcon(getClass().getResource("/imagenes/nododob.png"));
    ImageIcon img=(ImageIcon) imagen;
    ImageIcon img2 = (ImageIcon) imagen2;
    g.setColor(Color.white);
    g.fillRect(0, 0, getSize().width,getSize().height);
     
        int disNodo = 50,aumentoNodo = 115;
        
        int disNombre = 77,aumentoNombre=115;
        
        for (int i = 0; i < cont; i++) {
            if(i ==0){
                g.drawImage(img2.getImage(), 40, 35, 167, 50, this);
            
            
                
            }else{
                g.drawImage(img.getImage(), disNodo, 35, 148, 50, this);
            }

            disNodo += aumentoNodo;
            
            this.setSize(disNodo+200, 21);
                                    
            g.setColor(Color.blue);
            g.drawString(lc.get(i).dato.getNombres(), disNombre, 55);

            this.repaint();

            
            disNombre += aumentoNombre;

        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
